### ISSUE TITLE
La page load_list_json affiche trop de choses

### ISSUE THREAD

**Issue by MestourBS** [OrifInformatique/stock#112]
La page load_list_json permet de voir tous les utilisateurs qui ont fait un prêt, avec toutes leurs propriétés même s'ils ne sont pas utilisés où que ce soit.

**Comment by DidierViret** [comment]
Par exemple les infos de l'utilisateur qui a fait un prêt sont chargées dans le json est visibles dans les données en arrière-plan (F12), y compris sont mot de passe haché.
