### ISSUE TITLE
Regrouper les items similaires

### ISSUE THREAD

**Issue by jubnl** [OrifInformatique/stock#137]
Il y a beaucoup d'items similaires (par ex: les adaptateurs USB-PS/2, les bras Ergotron LX, etc..). 
Il faudrait pouvoir n'afficher qu'un seul item par "type" d'item dans la vue item/index.
Dans la vue d'un item il faudrait savoir combien d'items de ce type sont disponible et combien sont en prêt.

Par exemple : l'adaptateur USB-PS/2 je ne le vois qu'une seule fois dans les recherches et quand je clique sur cet item je peux voir qu'il y en a X disponible (et X en cours de prêt).

**Comment by SchindlerSimao** [comment]
Identique à l'issue #34
