### ISSUE TITLE
clean le fichier de structure ainsi que les datas à inserer dans la db 'Stock' 

### ISSUE THREAD

**Issue by jubnl** [OrifInformatique/stock#139]
Il faut clean/update ces 2 fichiers: 
- stock/database_structure/20200503_DATABASE_STRUCTURE_v16.sql
- stock/database_structure/SAMPLE_DATAS.sql

Il y a des données dupliquées, des champs inexistants etc etc.....

![sql_field](https://user-images.githubusercontent.com/66769052/91049358-6586e200-e61d-11ea-888b-d687b64d2660.PNG)
![sql_duplicata](https://user-images.githubusercontent.com/66769052/91049361-66b80f00-e61d-11ea-8781-3e5042d3cd02.PNG)
![sql_duplicata_2](https://user-images.githubusercontent.com/66769052/91049366-6750a580-e61d-11ea-81e4-fdddd9156524.PNG)

**Comment by DidierViret** [comment]
Abandonné en raison du passage à CI 4
