### ISSUE TITLE
Permettre l'exportation d'inventaire

### ISSUE THREAD

**Issue by DidierViret** [OrifInformatique/stock#30]
Ajouter une fonction qui permet d'exporter l'inventaire au format Excel ou csv.
L'exportation partielle doit être possible, selon les filtres proposés dans la liste des objets.

**Comment by RemyTombez** [comment]
La méthode fputcsv() permet de créer une ligne CSV à partir d'un tableau uni-dimensionnel : https://www.php.net/manual/fr/function.fputcsv.php

Ce lien StackOverflow aide beaucoup à voir comment créer un fichier CSV téléchargeable : 
https://stackoverflow.com/questions/4345554/convert-php-object-to-associative-array
