### ISSUE TITLE
Ajouter une fonctionnalité d'impression de fiche de prêt

### ISSUE THREAD

**Issue by DidierViret** [OrifInformatique/stock#39]
Ajouter la possibilité d'imprimer une fiche de prêt pour un ou plusieurs articles, qui pourra ensuite être signée par la personne à qui on prête du matériel.

La fiche devrait comprendre
- Le matériel en prêt et son état
- Le nom de l'emprunteur, une mention comme quoi il est responsable du matériel et doit le rendre dans le même état.
- La date de retour prévue
- Une partie pour le contrôle au moment du retour de matériel

**Comment by RemyTombez** [comment]
Il doit être possible de créer un document (en suite imprimable) à l'aide de FPDF : http://www.fpdf.org/
