### ISSUE TITLE
Corriger le filtrage des numéros d'inventaire

### ISSUE THREAD

**Issue by DidierViret** [OrifInformatique/stock#45]
Adapter le filtrage sur le numéro d'inventaire pour qu'il prenne en compte les nouveaux numéros d'inventaire composés du champ "inventory_number" et du champ "item_id".

**Comment by DidierViret** [comment]
Attention à penser aux différentes possibilités de recherche que pourrait faire un utilisateur.
Par exemple
- MACLA17.0004
- MACLA17
- 0004
- CLA17
- etc.

**Comment by RemyTombez** [comment]
Le filtre fonction dans les 4 cas en exemples, néanmoins si jamais l'utilisateur inscrit dans le champ une valeur qui contient un point et qui est vide à sa gauche (ex: ".0002") le filtre sort tout les résultats.

L'importance du problème ainsi que sa probabilité à se produire par erreur utilisateur est à juger.
