### ISSUE TITLE
Corriger nouvel objet toujours enregistrer comme fonctionnel (jusqu'à Patch-1.4)

### ISSUE THREAD

**Issue by RemyTombez** [OrifInformatique/stock#56]
Constaté d'abord sur la branche _inventoryControl_, un objet créé sera toujours enregistré comme _fonctionnel_.

Le problème existe dans la branche _Patch-1.3_, mais pas _Patch-1.4_.

Lors de l'intégration de la branche _inventoryControl_ dans le prochain patch, vérifier que le problème à été définitivement corrigé.

**Comment by DidierViret** [comment]
Bug corrigé dans patch 1.4
