### ISSUE TITLE
Cacher les filtres vide

### ISSUE THREAD

**Issue by MestourBS** [OrifInformatique/stock#62]
Dans le cas où un filtre ne contient rien, il n'y a aucune utilité à le sélectionner.

Exemple: quand le filtre "Logiciel téléchargeable" ne contient aucun objet.
![screenshot_1](https://user-images.githubusercontent.com/42637780/44662704-d84d2a80-aa0e-11e8-8f8b-07c81a9eb3b0.png)

**Comment by DidierViret** [comment]
On garde les lieux de stockage vides pour le cas ou il seraient utiles.
