### ISSUE TITLE
double view() et create() dans le dernier commit du patch 1.4

### ISSUE THREAD

**Issue by MestourBS** [OrifInformatique/stock#71]
Les fonctions `view()` et `create()` sont présente à double après l'ajout du dernier commit du patch 1.4.
Les déclarations de la fonction `view()` sont aux lignes 163 et 316.
Les déclarations de la fonction `create()` sont aux lignes 183 et 343.

**Comment by DidierViret** [comment]
Merci beaucoup pour votre analyse, qui va m'aider à corriger ce bug.

**Comment by DidierViret** [comment]
Corrigé le dédoublement des fonctions view() et create().
