### ISSUE TITLE
Corriger une erreur de pagination pour l'affichage des objets défectueux ou plus disponibles

### ISSUE THREAD

**Issue by DidierViret** [OrifInformatique/stock#94]
Si on sélectionne l'affichage d'objets défectueux ou plus disponibles puis qu'on change de page avec la pagination, le filtre revient tout seul sur "fonctionnel".

**Comment by RemyTombez** [comment]
Le problème provient du filtre PHP utilisé pour la branche master, la branche 1.6 corrige déjà le problème en raison du nouveau système de filtre qui fonctionne en local via JQuery.
